### PR TITLE
Update server.lua

### PR DESCRIPTION
**Pull request by cetvoropek**
Fixed error when script is started

### CODE REVIEW

**Comment by ticce77** [comment]
Did you put table to database? I have a similar problem and this didn't work for me.

**Comment by cetvoropek** [comment]
> Did you put table to database? I have a similar problem and this didn't work for me.

Put items in database, and go to the [modules/plants/server.lua] and on line 43 delete ." from the end of the line

**Comment by cetvoropek** [comment]
That worked for me

**Comment by ticce77** [comment]
OK,  It needed couple restarts and now it's working.

**Review by PickleModifications — APPROVED** [review]
Nice work!

**Pull request merged**
